steps:
  - name: ':docker: :package:'
    plugins:
      'docker-compose#v1.7.0':
        build: create-fusion-plugin
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - command: yarn flow check
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.7.0':
        run: create-fusion-plugin
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: create-fusion-plugin
    agents:
      queue: workers
  - name: ':jest:'
    command: yarn jest
    plugins:
      'docker-compose#v1.7.0':
        run: create-fusion-plugin
    agents:
      queue: workers
