steps:
  - name: ':docker: build'
    plugins:
      'docker-compose#v1.7.0':
        build: fusion-apollo-universal-client
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - name: ':flowtype:'
    command: yarn flow
    plugins:
      'docker-compose#v1.5.2':
        run: fusion-apollo-universal-client
    agents:
      queue: workers
  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-apollo-universal-client
    agents:
      queue: workers
  - name: ':node:'
    command: yarn test
    plugins:
      'docker-compose#v1.7.0':
        run: fusion-apollo-universal-client
    agents:
      queue: workers
