language: node_js
sudo: false
node_js:
  - 8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
script:
  - yarn run bootstrap
  - yarn run test
