version: '2'
services:
  create-fusion-plugin:
    build: .
    volumes:
      - .:/create-fusion-plugin
      - /create-fusion-plugin/node_modules/
      - /create-fusion-plugin/templates/plugin/content/node_modules/
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
