steps:
  - name: ':docker: build'
    plugins:
      'docker-compose#v1.7.0':
        build: eslint-config-fusion
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
    agents:
      queue: builders
  - wait
  - command: yarn flow
    name: ':flowtype:'
    plugins:
      'docker-compose#v1.7.0':
        run: eslint-config-fusion
    agents:
      queue: workers
  - name: ':eslint:'
    command: npm run lint
    plugins:
      'docker-compose#v1.7.0':
        run: eslint-config-fusion
    agents:
      queue: workers
